n = input('digite algum : ')
print('o tipo primitivo desse valor e :',type(n))
print('isso e um numero ?',n.isnumeric())
print('isso e uma letra ?',n.isalpha())
print('isso e espaço ?',n.isspace())
print('isso e numero e letra ?',n.isalnum())
print('estar em maiusculas ?',n.isupper())
print('estar em minusculas ?',n.islower())
print('estar capitalizada ?',n.istitle())
